version: "3.8"

services:
  coreapp:
    container_name: homepage
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - SKIP_PREFLIGHT_CHECK=true
      - PORT=4000
